name: Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run pro komplet report
        run: |
          bandit -r ./app.py -f html -o bandit-report.html

      - name: Run pro fail check
        run: |
          bandit -r ./app.py -s H || exit 1

      - name: uploadnout report at to dopadne jakkoli
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.html