name: Bandit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        id: bandit_scan
        run: |
          bandit -r ./app.py -lll -f html -o bandit-report.html || echo "BANDIT_FAILED=true" >> $GITHUB_ENV
        
      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.html

      - name: fail az po uploadu
        if: env.BANDIT_FAILED == 'true'
        run: |
          echo "Bandit nasel kritikal, stopuju job."
          exit 1